all:
	cd fonts; make -f Makefile
	cd rotozoom; make -f Makefile
	cd framerate; make -f Makefile
	cd primitives; make -f Makefile

clean:
	cd fonts; make -f Makefile clean
	cd rotozoom; make -f Makefile clean
	cd primitives; make -f Makefile clean
	cd framerate; make -f Makefile clean
run:
	cd rotozoom; make -f Makefile run

